DocCare/DocCare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('department/',include("departments.url")),
    path('doctor/',include("doctors.url")),
    path('dashboard/',include("dashboards.urls")),
    path("patient/",include("patients.urls")),
    path("",include("credentials.urls")),

]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

DocCare/credentials/urls.py
from django.urls import path
from credentials import views

app_name="credentials"

urlpatterns=[
    path("register",views.register,name="signup"),
    path("login",views.login,name="signin"),
    path("logout",views.logout,name="signout"),
    path("",views.home,name="home_page")
]

DocCare/dashboards/urls.py
from django.urls import path
from dashboards import views

app_name="dashboards"

urlpatterns=[
    path("manager-dashboard",views.managerDashboard,name="manager_dashboard"),
]

DocCare/patients/urls.py
from django.urls import path
from . import views

app_name="patients"

urlpatterns=[
    path("add-patient",views.add_patients,name="new_patient"),
    path("edit-patient/<int:patient_id>",views.edit_patient,name="edit_patient"),
    path("list-patients",views.listpatients,name="all_patients"),
    path("patient-detail/<int:patient_id>",views.viewPatient,name="patient_details"),
    path("delete-patient/<int:patient_id>",views.deletePatient,name="delete_patient")
]

DocCare/dashboards/models.py
from django.db import models

# Create your models here.

DocCare/dashboards/views.py
from django.shortcuts import render

# Create your views here.
def managerDashboard(request):
    return render(request,"dashboards/manager_dashboard.html")

DocCare/templates/dashboards/manager_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
         <a href="{% url 'departments:add_dep' %}">Add Department</a>
        <a href="{% url 'doctors:add_doctor' %}">Add Doctor</a>
        <a href="{% url 'patients:all_patients' %}">All Patients</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'credentials:signout' %}">Logout</a>
        {% endif %}
    </nav>
    <div>
        <h1>Manager Dashboard</h1>
    </div>
</body>
</html>