DocCare/DocCare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('department/',include("departments.url")),
    path('doctor/',include("doctors.url")),
    path('dashboard/',include("dashboards.urls")),
    path("patient/",include("patients.urls")),
    path("",include("credentials.urls")),

]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

DocCare/patients/urls.py
from django.urls import path
from . import views

app_name="patients"

urlpatterns=[
    path("add-patient",views.add_patients,name="new_patient"),
    path("edit-patient/<int:patient_id>",views.edit_patient,name="edit_patient"),
    path("list-patients",views.listpatients,name="all_patients"),
    path("patient-detail/<int:patient_id>",views.viewPatient,name="patient_details"),
    path("delete-patient/<int:patient_id>",views.deletePatient,name="delete_patient")
]

DocCare/patients/models.py
from django.db import models

# Create your models here.
class Patient(models.Model):
    GENDER_CHOICES=(
        ("male","Male"),
        ("female","Female"),
        ("other","Other")
    )
    patient_code =models.CharField(max_length=20,unique=True)
    name=models.CharField(max_length=60)
    dob=models.DateField()
    gender=models.CharField(max_length=10,choices=GENDER_CHOICES)
    phone=models.CharField(max_length=14)
    address=models.TextField()
    created_at=models.DateField(auto_now_add=True)
    is_active=models.BooleanField(default=True)

DocCare/patients/forms.py
from django import forms
from patients.models import Patient

class PatientForm(forms.ModelForm):
    class Meta:
        model=Patient
        fields=[
        "name",
        "dob",
        'gender',
        'phone',
        'address',
        ]
        widgets={
            "dob":forms.DateInput(attrs={"type":"date"})
        }

DocCare/patients/views.py
from django.shortcuts import render,redirect
from patients.forms import PatientForm
from django.http import HttpResponse
from django.contrib import messages
from patients.models import Patient
# Create your views here.

def add_patients(request):
    if request.method=="POST":
        p_form=PatientForm(request.POST)
        if p_form.is_valid():
            p_form.save()
            messages.info(request,"New Patient Added")
    else:
        p_form=PatientForm()
    return render(request,"patients/add_patients.html",{"pf_form":p_form})

def edit_patient(request,patient_id):
    patient=Patient.objects.get(id=patient_id)
    if request.method=="POST":
        p_form=PatientForm(request.POST,instance=patient)
        if p_form.is_valid():
            p_form.save()
            return redirect("patients:patient_details",patient_id)
    else:
        p_form=PatientForm(instance=patient)
    return render(request,"patients/edit_patient.html",{"pf_form":p_form})

def viewPatient(request,patient_id):
    patient=Patient.objects.get(id=patient_id)
    return render(request,"patients/view_patient.html",{"patient":patient})

def listpatients(request):
    all_patients=Patient.objects.all()
    return render(request,"patients/list_patient.html",{"patients":all_patients})

def deletePatient(request,patient_id):
    patient=Patient.objects.get(id=patient_id)
    patient.delete()
    return redirect("patients:all_patients")

DocCare/templates/patients/add_patients.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for msg in messages %}
        {{msg}}
    {% endfor %}
    <h1>Add patients</h1>
    <form method="post" action="{% url 'patients:new_patient' %}">
            {% csrf_token %}
            {{pf_form.as_p}}
            <input type="submit" value="Register">
    </form>
</body>
</html>

DocCare/templates/patients/edit_patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DocCare:Edit Patient details</title>
</head>
<body>
    <div>
        <h1>Edit Patient</h1>
        <form method="post" action="">
            {% csrf_token %}
            {{pf_form.as_p}}
            <input type="submit" value="Save Changes">
        </form>
    </div>
</body>
</html>

DocCare/templates/patients/list_patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div>
        <h1>All Patients</h1>
        <div>
            <table border="1" cellpadding="8">
                <thead>
                    <tr>
                        <th>Patient Code</th>
                        <th>Name</th>
                        <th>Gender</th>
                        <th>Phone</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for patient in patients %}
                    <tr>
                        <td>{{ patient.patient_code }}</td>
                        <td>{{ patient.name }}</td>
                        <td>{{ patient.gender|title }}</td>
                        <td>{{ patient.phone }}</td>
                        <td>
                            <a href="{% url 'patients:patient_details' patient.id %}">View</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">No patients found</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

DocCare/templates/patients/view_patient.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
 
    <div>
        <h1>Patient Details</h1>

        <p><strong>Patient Code:</strong> {{ patient.patient_code }}</p>
        <p><strong>Name:</strong> {{ patient.name }}</p>
        <p><strong>Date of Birth:</strong> {{ patient.dob }}</p>
        <p><strong>Gender:</strong> {{ patient.gender|title }}</p>
        <p><strong>Phone:</strong> {{ patient.phone }}</p>
        <p><strong>Address:</strong> {{ patient.address }}</p>
        <p><strong>Registered On:</strong> {{ patient.created_at }}</p>


    </div>
    <div>
        <a href="{% url 'patients:edit_patient' patient.id %}">Edit Details</a>
        <a href="{% url 'patients:delete_patient' patient.id %}">Delete</a>
    </div>
</body>
</html>