DocCare/DocCare/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('department/',include("departments.url")),
    path('doctor/',include("doctors.url")),
    path('dashboard/',include("dashboards.urls")),
    path("patient/",include("patients.urls")),
    path("",include("credentials.urls")),

]


urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

DocCare/credentials/urls.py
from django.urls import path
from credentials import views

app_name="credentials"

urlpatterns=[
    path("register",views.register,name="signup"),
    path("login",views.login,name="signin"),
    path("logout",views.logout,name="signout"),
    path("",views.home,name="home_page")
]

DocCare/dashboards/urls.py
from django.urls import path
from dashboards import views

app_name="dashboards"

urlpatterns=[
    path("manager-dashboard",views.managerDashboard,name="manager_dashboard"),
]

DocCare/credentials/models.py
from django.db import models

# Create your models here.

DocCare/credentials/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.contrib import auth
from django.contrib import messages


# Create your views here.

def register(request):
    if request.method=="POST":
        first_name=request.POST["f_name"]
        last_name=request.POST["l_name"]
        email=request.POST["email"]
        password=request.POST["password"]
        if User.objects.filter(username=email).exists():
            messages.info(request,"Username already exist")
        else:
            user=User.objects.create_user(username=email,first_name=first_name,last_name=last_name,password=password)
            # print(user)
            user.save()
            return redirect("credentials:signin")
    return render(request,"credentials/register.html")

def login(request):
    if request.method=="POST":
        email=request.POST["username"]
        password=request.POST["password"]
        user=auth.authenticate(username=email,password=password)
        # print(user)
        if user is not None:
            auth.login(request,user)
            return redirect("dashboards:manager_dashboard")
        else:
            messages.info(request,"Invalid Credentials")
    return render(request,"credentials/login.html")

def logout(request):
    auth.logout(request)
    return redirect("credentials:signin")

def home(request):
    return render(request,"credentials/index.html")

DocCare/templates/credentials/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
     <nav>
        
        {% if request.user.is_authenticated %}
            <a href="{% url 'dashboards:manager_dashboard' %}">Dashboard</a>
            <a href="{% url 'credentials:signout' %}">Logout</a>
        {% else %}
            <a href="{% url 'credentials:signup' %}">Register</a>
            <a href="{% url 'credentials:signin' %}">Login</a>
        {% endif %}
    </nav>
    <h1>Welcome to DocCare</h1>
</body>
</html>

DocCare/templates/credentials/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
</head>
<body>

<h2>User Login</h2>
{% for msg in messages %}
    {{msg}}
{% endfor %}
<form method="post" action="{% url 'credentials:signin' %}">
    {% csrf_token %}

    <label>Username:</label><br>
    <input type="text" name="username" required><br><br>

    <label>Password:</label><br>
    <input type="password" name="password" required><br><br>

    <button type="submit">Login</button>
</form>

<p>
    Don’t have an account?
    <a href="{% url 'credentials:signup' %}">Register</a>
</p>

</body>
</html>

DocCare/templates/credentials/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Register</title>
</head>
<body>

<h2>User Registration</h2>
{% for msg in messages %}
    {{msg}}
{% endfor %}
<form method="post" action="{% url 'credentials:signup' %}" onsubmit="return comparePasswords()">
    {% csrf_token %}

    <label>First name:</label><br>
    <input type="text" name="f_name" required><br><br>

    <label>Last name:</label><br>
    <input type="text" name="l_name" required><br><br>

    <label>Email:</label><br>
    <input type="email" name="email" required><br><br>

    <label>Password:</label><br>
    <input type="password" name="password" id="password" required><br><br>

    <label>Confirm Password:</label><br>
    <input type="password" name="confirm_password" id="confirm_password" required><br><br>

    <button type="submit">Register</button>
</form>

<p>
    Already have an account?
    <a href="{% url 'credentials:signin' %}">Login</a>
</p>
<script>
    function comparePasswords(){
        const password=document.getElementById("password").value
        const con_passwd=document.getElementById("confirm_password").value
        if(password==con_passwd){
            return true
        }
        else{
            alert("Password and Confirm password must be same")
            return false
        }
    }
</script>
</body>
</html>